### ISSUE TITLE
WriteSingleCoilAsync missing

### ISSUE THREAD

**Issue by NickCrane66** [NModbus/NModbus.v4#18]
The extension method for WriteSingleCoilAsync is missing from IModbusClientExtensions.

Some other comments on the new NModbus.

Not sure about having to pass ILoggerFactory to the connection strategy, transports and ModbusClient. 
My client wrapper has an ILogger already, but for this new code pattern I have had to pass the ILoggerFactory in too.
Could this be changed to use ILogger?

Love the change to all async, even thought its a major breaking change.
Love NModbus. I have been using it for quit a few years.

Do you have any idea when a release version might be available?

**Comment by rquackenbush** [comment]
> The extension method for WriteSingleCoilAsync is missing from IModbusClientExtensions.

Thank you for checking out the code in general and pointing that out in particular. I will happily add that as soon as possible.

> Not sure about having to pass ILoggerFactory to the connection strategy, transports and ModbusClient.
> My client wrapper has an ILogger already, but for this new code pattern I have had to pass the ILoggerFactory in too.
> Could this be changed to use ILogger?

I don't love how I've set up the logging bits. The history: 
- I started out with `ILogger<T>`. This made the calling code particularly annoying because having to create a typed instance was unwieldly (e.g. `new ModbusClient(loggerFactory.CreateLogger<ModbusClient>)`.
- Just passing `ILogger` means we would lose context - namely _what_ was doing the logging. This might be an acceptable tradeoff, but I haven't gotten there yet.
- This led to `ILoggerFactory`. This allows for a consistent experience when creating NModbus objects. That said, it's a departure from the past and does still put some work on the caller.
- In the current version of NModbus, I use the factory pattern to get around the need for passing logging bits explicitly around. I'm trying to avoid using factories for this version as it feels too prescriptive / dogmatic to require a factory. I also wanted to enable dependency injection for users who want to go down that road.

Do you have any other ideas for how to approach this? 

> Love the change to all async, even thought its a major breaking change.

Yay! I'm pretty happy with it so far. I'm trying hard to keep the library 100% async as having the non-async method bloats the code quite a bit. That said, if enough users request it, I'll add it back in.

> Love NModbus. I have been using it for quit a few years.

Thank you! I'm a fan too. I was using the library for quite a while when the previous maintainer went dark. It has been a struggle maintaining the project without having more test equipment, but maybe I can find a sponsor for that in the future.

> Do you have any idea when a release version might be available?

Unfortunately, no. I want to get the serial bits up and running before I make a release version for a number of reasons:
- I want to make sure I don't break a released interface if I need to retrofit something in to make serial work.
- I'd like to do a better job separating the Modbus protocol (RTU/ASCII/MBAP) from the underlying transport (UDP/TCP/Serial).
- Do lots of testing

Thank you for filing this issue and your interest in NModbus!

**Comment by MPapst** [comment]
I also came across that ILoggerFactory thing. 
What about using a factory pattern to create the necessary instances?

An IModbusClientFactory and an IModbusServerFactory could create all the instances and could itself be created using DI.
Maybe I can try that a Bit tomorrow and submit a PR.

**Comment by rquackenbush** [comment]
WriteSingleCoilAsync is available as of version `v4.0.0-alpha009` of the package.

**Comment by rquackenbush** [comment]
Created separate issue for ILoggerFactory: https://github.com/NModbus/NModbus.v4/issues/20
